### ISSUE TITLE
Error in adding members to Teams private channel command

### ISSUE THREAD

**Issue by Vignesh0791** [gihanrcg/MSTeamsBulkUser#1]
Getting error while running the addMembersToPrivateChannel.ps1 :
The term 'Add-TeamChannelUser' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by gihanrcg** [comment]
This command is still in the beta release of the team's PowerShell module. You might need to update your module.

**Comment by gihanrcg** [comment]
Try this 
```
Install-Module -Name MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease -force -Allo
wClobber
```

**Comment by Vignesh0791** [comment]
Thank you for your quick response!
![image](https://user-images.githubusercontent.com/71837389/108070213-4461f400-708a-11eb-8c76-6d9baffc875b.png)
I am still getting the same error after trying the above command.

**Comment by gihanrcg** [comment]
Please read this. This will solve your problem [https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps#description]( https://docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps#description)

**Comment by gihanrcg** [comment]
And here is the way to install the public preview of the Teams module [https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install#install-teams-powershell-public-preview]( https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install#install-teams-powershell-public-preview)
